### ISSUE TITLE
When would you plan to open the code?

### ISSUE THREAD

**Issue by yukitsuji** [ucbdrive/hd3#1]
Thank you for planning to share the source code.
This work is so amazing and I would like to check your code.

Could you share the day you plan to open your code?
Thanks,
Yuki

**Comment by yzcjtr** [comment]
Hi Yuki, thanks for your interest in our work. Sorry for falling behind the previous schedule. We will release our code this week. I promise! 🤣

**Comment by yzcjtr** [comment]
Code has been released. We will provide the pretrained model in the next few days.

**Comment by yukitsuji** [comment]
Thank you very much!
