### ISSUE TITLE
How to visualize Confidence Map?

### ISSUE THREAD

**Issue by kwea123** [ucbdrive/hd3#10]
Hi, I wonder how to visualize the Confidence Map like in the paper?
I am using optical flow, and I suppose I should get it here:
https://github.com/ucbdrive/hd3/blob/1b0185d5ed24148895dc6ae573a315ddb99f8a01/hd3model.py#L36-L37

but the `result['prob']` is a tensor that has 81 channels...

Can you help me with this? Thanks.

**Comment by kwea123** [comment]
found the answer.
https://github.com/ucbdrive/hd3/blob/2874b6b5186d02b7499562af40fbd48d85798dba/utils/visualizer.py#L44-L48

**Comment by amaanda** [comment]
@kwea123 were you able to save the output confidence map?

**Comment by kwea123** [comment]
Yes, just need to do that piece of code I found. It gives an array of shape (H,W).

**Comment by amaanda** [comment]
@kwea123 i tried adding the line `visualizer.get_visualization(img_list=resized_img_list,label_list=label_list,ms_vect=output['vect'],ms_prob=output['prob'])` to inference.py, but it doesn't work. could you please share how you did it? thanks!

**Comment by amaanda** [comment]
@kwea123 i tried adding the line visualizer.get_visualization(img_list=resized_img_list,label_list=label_list,ms_vect=output['vect'],ms_prob=output['prob']) to inference.py, but it doesn't work. could you please share how you did it? thanks!

**Comment by kwea123** [comment]
I recoded this part by myself in [jupyter notebook](https://nbviewer.jupyter.org/github/kwea123/hd3/blob/master/flow_prediction.ipynb).
The cells 199,200,182 are what you want.

**Comment by amaanda** [comment]
@kwea123 yes, in order to get that i tried get_prob=True and get_vis=True in
https://github.com/ucbdrive/hd3/blob/1b0185d5ed24148895dc6ae573a315ddb99f8a01/hd3model.py#L23-L30

but i get the following error:
`gt_flo, valid_mask = downsample_flow(label_list[0]`
`IndexError: list index out of range`

**Comment by amaanda** [comment]
@kwea123 i will check that out then. thanks for sharing your solution!

**Comment by kwea123** [comment]
I didn't use their code so I can't tell you why the error appears.. but I can guarantee my code, you just need to change the image paths.
