### ISSUE TITLE
encoder probelm in the train.py

### ISSUE THREAD

**Issue by bbidong** [ucbdrive/hd3#13]
Hi, in the model training, we need to initialize the weights from a pretrained model via --pretrain , if the encoder is dla, i can obtain pretrained model by **download_models.sh** in the model zoo.
But if I want to train a new model whose encoder is **vgg**, there is not pretrained model in model zoo , and what should I do ??

**Comment by yzcjtr** [comment]
Just randomly initialize the model weights. I think there wouldn't be significant differences in terms of the final performance. Or you can find a pretrained VGG model elsewhere and write your customized vgg.py which is compatible with that model.
