### ISSUE TITLE
error when run inference

### ISSUE THREAD

**Issue by hagianga21** [ucbdrive/hd3#19]
Hi, I downloaded model zoo and run this script fro inference (pytorch 1.0.1, cuda 9.0 python 3.6):
python -u inference.py \
  --task=stereo \
  --data_root=/home/gtruong/project/hd3 \
  --data_list=lists/giang.txt \
  --context \
  --encoder=dlaup \
  --decoder=hda \
  --batch_size=1 \
  --workers=16 \
  --flow_format=png \
  --model_path=/home/gtruong/project/hd3/model_zoo/hd3s_things_kitti-1243813e.pth \
  --save_folder=/home/gtruong/project/hd3/giang

The error I got:
[2019-08-29 14:55:17,755 INFO inference.py line 127 502088] => loading checkpoint 'D:\Reimplement\hd3/model_zoo/hd3s_things_kitti-1243813e.pth'
Traceback (most recent call last):
  File "inference.py", line 243, in <module>
    main()
  File "inference.py", line 129, in main
    model.load_state_dict(checkpoint['state_dict'], strict=True)
  File "C:\Users\Giang\Anaconda3\envs\basic\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.hd3net.Decoder_5.dc_conv_0.0.weight", "module.hd3net.Decoder_5.dc_conv_0.1.weight", "module.hd3net.Decoder_5.dc_conv_0.1.bias", "module.hd3net.Decoder_5.dc_conv_0.1.running_mean", "module.hd3net.Decoder_5.dc_conv_0.1.running_var", "module.hd3net.Decoder_5.dc_conv_1.0.weight", "module.hd3net.Decoder_5.dc_conv_1.1.weight", "module.hd3net.Decoder_5.dc_conv_1.1.bias", "module.hd3net.Decoder_5.dc_conv_1.1.running_mean", "module.hd3net.Decoder_5.dc_conv_1.1.running_var", "module.hd3net.Decoder_5.dc_conv_2.0.weight", "module.hd3net.Decoder_5.dc_conv_2.1.weight", "module.hd3net.Decoder_5.dc_conv_2.1.bias", "module.hd3net.Decoder_5.dc_conv_2.1.running_mean", "module.hd3net.Decoder_5.dc_conv_2.1.running_var", "module.hd3net.Decoder_5.dc_conv_3.0.weight", "module.hd3net.Decoder_5.dc_conv_3.1.weight", "module.hd3net.Decoder_5.dc_conv_3.1.bias", "module.hd3net.Decoder_5.dc_conv_3.1.running_mean", "module.hd3net.Decoder_5.dc_conv_3.1.running_var", "module.hd3net.Decoder_5.dc_conv_4.0.weight", "module.hd3net.Decoder_5.dc_conv_4.1.weight", "module.hd3net.Decoder_5.dc_conv_4.1.bias", "module.hd3net.Decoder_5.dc_conv_4.1.running_mean", "module.hd3net.Decoder_5.dc_conv_4.1.running_var", "module.hd3net.Decoder_5.dc_conv_5.0.weight", "module.hd3net.Decoder_5.dc_conv_5.1.weight", "module.hd3net.Decoder_5.dc_conv_5.1.bias", "module.hd3net.Decoder_5.dc_conv_5.1.running_mean", "module.hd3net.Decoder_5.dc_conv_5.1.running_var", "module.hd3net.Decoder_5.dc_conv_6.0.weight", "module.hd3net.Decoder_5.dc_conv_6.1.weight", "module.hd3net.Decoder_5.dc_conv_6.1.bias", "module.hd3net.Decoder_5.dc_conv_6.1.running_mean", "module.hd3net.Decoder_5.dc_conv_6.1.running_var", "module.hd3net.Decoder_5.cls.weight", "module.hd3net.Decoder_5.cls.bias".
        Unexpected key(s) in state_dict: "module.hd3net.Decoder_5.mapping.block1.conv1.weight", "module.hd3net.Decoder_5.mapping.block1.bn2.weight", "module.hd3net.Decoder_5.mapping.block1.bn2.bias", "module.hd3net.Decoder_5.mapping.block1.bn2.running_mean", "module.hd3net.Decoder_5.mapping.block1.bn2.running_var", "module.hd3net.Decoder_5.mapping.block1.bn2.num_batches_tracked", "module.hd3net.Decoder_5.mapping.block1.conv2.weight", "module.hd3net.Decoder_5.mapping.block1.shortcut.0.weight", "module.hd3net.Decoder_5.mapping.block2.bn1.weight", "module.hd3net.Decoder_5.mapping.block2.bn1.bias", "module.hd3net.Decoder_5.mapping.block2.bn1.running_mean", "module.hd3net.Decoder_5.mapping.block2.bn1.running_var", "module.hd3net.Decoder_5.mapping.block2.bn1.num_batches_tracked", "module.hd3net.Decoder_5.mapping.block2.conv1.weight", "module.hd3net.Decoder_5.mapping.block2.bn2.weight", "module.hd3net.Decoder_5.mapping.block2.bn2.bias", "module.hd3net.Decoder_5.mapping.block2.bn2.running_mean", "module.hd3net.Decoder_5.mapping.block2.bn2.running_var", "module.hd3net.Decoder_5.mapping.block2.bn2.num_batches_tracked", "module.hd3net.Decoder_5.mapping.block2.conv2.weight", "module.hd3net.Decoder_5.mapping.root.0.weight", "module.hd3net.Decoder_5.mapping.root.0.bias", "module.hd3net.Decoder_5.mapping.root.0.running_mean", "module.hd3net.Decoder_5.mapping.root.0.running_var", "module.hd3net.Decoder_5.mapping.root.0.num_batches_tracked", "module.hd3net.Decoder_5.mapping.root.2.weight",
"module.hd3net.Decoder_5.cls.0.weight", "module.hd3net.Decoder_5.cls.0.bias", "module.hd3net.Decoder_5.cls.0.running_mean", "module.hd3net.Decoder_5.cls.0.running_var", "module.hd3net.Decoder_5.cls.0.num_batches_tracked", "module.hd3net.Decoder_5.cls.2.weight", "module.hd3net.Decoder_5.cls.2.bias".

**Comment by hagianga21** [comment]
I fixed it. Thanks

**Comment by ryx2** [comment]
Hey @hagianga21  I have this same problem, how did you get around to fixing it?

**Comment by hagianga21** [comment]
Hi, it's a long time ago and I totally forgot. I think you start debugging with "context". They set initial "context" to be False
