### ISSUE TITLE
Regarding feature map resolution from DLA encoder

### ISSUE THREAD

**Issue by ChengyaoLi** [ucbdrive/hd3#21]
Hello again, is there a particular reason that the highest resolution of the feature map coming from the DLA encoder is half size of the original input? Thanks!

https://github.com/ucbdrive/hd3/blob/9239852735dcd97e29bd01249c60ded739e28734/models/dla_up.py#L138

**Comment by ChengyaoLi** [comment]
I should probably ask the author of dla, but I am curious what's your taking on the effect of estimating the disparity map with a lower resolution and then upscale it, which I think is what hd3 does.

**Comment by yzcjtr** [comment]
I'm not sure what your question is. But we use dla-up as the encoder instead of pure dla. You can refer to the original paper to figure out the resolution detail. As for the upsampling, it's infeasible and redundant to perform prediction in full-resolution due to computation and memory issues.

**Comment by ChengyaoLi** [comment]
Thanks. That pretty much answers my question
