### ISSUE TITLE
Some Results and Questions

### ISSUE THREAD

**Issue by yanqswhu** [ucbdrive/hd3#26]
Thanks for your wonderful work!

I download your code and test it under some image pairs captured by myself, but the results is not very good compared to the flownet2 ( https://github.com/NVIDIA/flownet2-pytorch ). 

Can you give me some advises about how to improve the result based on your code ?
Thanks.

Pair 1:
![left1](https://user-images.githubusercontent.com/17909171/71517453-0e433d00-28e9-11ea-8768-08e62c5d2eb0.jpg)
![righ1](https://user-images.githubusercontent.com/17909171/71517464-1b602c00-28e9-11ea-9355-6d87c15b5a60.jpg)

Results of FLowNet2
![flow1](https://user-images.githubusercontent.com/17909171/71517512-56faf600-28e9-11ea-8c92-7541ef76d46a.png)

Results of hd3
![left1](https://user-images.githubusercontent.com/17909171/71517530-74c85b00-28e9-11ea-8f93-462250e32315.png)

-----

Pair 2:
![left4](https://user-images.githubusercontent.com/17909171/71517478-2adf7500-28e9-11ea-9030-94719293b8b5.jpg)
![righ4](https://user-images.githubusercontent.com/17909171/71517484-2f0b9280-28e9-11ea-815e-d7a9a79495be.jpg)

FlowNet2
![flow4](https://user-images.githubusercontent.com/17909171/71517560-91fd2980-28e9-11ea-9852-b31ee3d2486b.png)

dh3
![left4](https://user-images.githubusercontent.com/17909171/71517558-8ad61b80-28e9-11ea-83c4-a1c4150edde3.png)

**Comment by yzcjtr** [comment]
Hi @Yannnnnnnnnnnn, thanks for your interest. 

1. Which model did you use to get these results? Have you tried using the model only trained on the synthetic datasets or finetuned only on Sintel? The model finetuned on KITTI would show some artifacts in the upper part as shown in your result.
2. What is the resolution of your input image pair? The result can be sensitive towards different max displacements. Keeping the resolution similar to the dataset the network has been trained on can help. Or you can try multi-scale test and see if the results are distinctively different.
3. As for the comparison with PWCNet, the provided model is trained on a mixture of different datasets (to participate in a challenge I remember), making their model more generalizable. I haven't had time for that. Welcome to share your model if you are interested in that.
4. Further improvement: please refer to this paper: https://arxiv.org/abs/1912.10739. They achieve state-of-the-art results based on our HD3 framework.
