### ISSUE TITLE
Question about how occlusion is handled

### ISSUE THREAD

**Issue by mli0603** [ucbdrive/hd3#31]
Dear authors:

Thank you very much for sharing your code! I have a question about how HD3 handles occlusion. 

Reading you code and paper, after the cost volume is constructed, it seems the decoder uses 2D convolution to find the match density, which is then converted to motion vectors. What if there is occlusion where no ground truth motion vector can be found? E.g. in stereo matching, left images usually have unmatched region on the left. Can you share some insights?

Thank you again!

**Comment by yzcjtr** [comment]
Hi, that is a good question. We didn't spend much effort in handling occlusions in this work. Instead, we let the context module to hallucinate those motions. It can help to some extent, but the more context you rely on, the easier your network tends to overfit. As seen in the benchmark, hd3 and its variants still rank top in KITTI if you check the non-occluded/foreground entries. With that said, we push the limits of non-occluded matching, but occlusion is not emphasis in this work. Would be interesting to see if special occlusion design proposed by other works can further improve performance in our hd3 framework.

**Comment by mli0603** [comment]
Thank you so much for your reply! This is very helpful :)
