### ISSUE TITLE
Large EPE error for stereo task

### ISSUE THREAD

**Issue by mli0603** [ucbdrive/hd3#32]
Hi,

Thanks for your code! When I run the inference code to evaluate disparity estimation on sceneflow dataset, the EPE is very large (it is 121 from a test image) from line 42 (https://github.com/ucbdrive/hd3/blob/master/hd3model.py#L42). I visualized the output of the network `curr_vect`, I see all estimation are negative (https://github.com/ucbdrive/hd3/blob/master/inference.py#L197). I can confirm I am using the stereo network since I am using the model `hd3sc_things-57947496.pth` with context mode on.

Is the EPE reported using pixel? Is this normal? I am not sure if the EPE is only for optical flow or can be used for disparity estimation as well. 

Thank you very much!

**Comment by mli0603** [comment]
It seems like during EPE calculation, the `output` is negative disparity, while the ground truth is positive. I inverted the sign the error becomes much smaller. 

Is this a problem of data or this is a mistake in EPE calculation?

**Comment by yzcjtr** [comment]
Hi, the EPE metric shouldn't be that large. The implementation should support both optical flow and stereo matching tasks. I guess you are using the original scene flow dataset instead of its subset. Please refer to a related discussion here (https://github.com/ucbdrive/hd3/issues/27).

**Comment by mli0603** [comment]
@yzcjtr Oh yes, this is exactly the problem. Thank you very much! I appreciate it.
