### ISSUE TITLE
replace FunctionCorrelation cupy GPU

### ISSUE THREAD

**Issue by duongpaKikai** [ucbdrive/hd3#33]
We have run hd3 with us video and result very good
We want to convert hd3 => TorchScript to add us program run in C++  demo for boss
But when script model we get error with `re.search('(SIZE_)([0-4])(\()([^\)]*)(\))', strKernel)` **in cupy of _FunctionCorrelation**

So whether have way replace calculate Correlation with cupy. just use operator between tensor with tensor on cpu

many thank

**Comment by yzcjtr** [comment]
Maybe this CPU implementation of correlation (https://github.com/ClementPinard/Pytorch-Correlation-extension) can serve your purpose?

**Comment by duongpaKikai** [comment]
@yzcjtr 
thank for your help
but i need implementation under form like _operator of tensor pytorch_ 
because i want convert to Script model
(Script model not support cupy)

**Comment by yzcjtr** [comment]
I believe the implementation I referenced above doesn't use cupy. It should support CPU execution as well.
Anyway, there's no off-the-shelf correlation operator in official PyTorch till now I believe. Though you can find one in tensorflow addons (https://www.tensorflow.org/addons/api_docs/python/tfa/layers/CorrelationCost).

**Comment by duongpaKikai** [comment]
@yzcjtr 
its so helpfull
Thank for your help
