### ISSUE TITLE
pretrained weights for pyramid  feature extractor

### ISSUE THREAD

**Issue by hofingermarkus** [ucbdrive/hd3#7]
First of all, thank you for sharing the weights of your fully trained models!

I was wondering if you could also share the pre-trained weights of your base feature extractor (DLA-34-Up) that you use at the start of your training. In your paper you state that you use an ImageNet pretrained model for this. 
I did find pre-trained weights for [DLA-34](http://dl.yf.io/dla/models/imagenet/) which should be similar to DLA-34-Up except for the upsampling, but I'm not quite sure if this is what you meant and used.

It would be great if you could add the DLA-34-Up base model for the feature extractor or maybe add a few words/links to your Readme if the DLA-34 version is what you used.

Thank you

**Comment by yzcjtr** [comment]
Hi, thanks so much for the suggestion! The DLA-34 you referenced is exactly what we used. The upsampling parameters are randomly initialized. I have added relevant descriptions in the readme file.

**Comment by hofingermarkus** [comment]
Thank you!
